[package]
name = "shazam-fpgen"
version = "1.0.0"
authors = ["Faisal Arshed <faisalarshed28@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
byteorder = "1.4.3"
chfft = "0.3.4"
crc32fast = "1.3.2"
wasm-bindgen = "0.2.83"
